# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rec_recipe.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10rec_recipe.proto\"4\n\x0cSimQueryResp\x12\r\n\x05match\x18\x01 \x01(\x08\x12\x15\n\rsim_word_list\x18\x02 \x03(\t\"\x16\n\x05Query\x12\r\n\x05query\x18\x01 \x01(\t\"\x19\n\x08UnitList\x12\r\n\x05units\x18\x01 \x03(\t\"6\n\nIngredient\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\"u\n\x0bIngredients\x12\x32\n\x0bingredients\x18\x01 \x03(\x0b\x32\x1d.Ingredients.IngredientsEntry\x1a\x32\n\x10IngredientsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\"A\n\x13UserLikeIngredients\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04unit\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\"$\n\x06Recipe\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t2\xab\x01\n\tRecRecipe\x12!\n\x08\x66ix_name\x12\x06.Query\x1a\r.SimQueryResp\x12\"\n\rget_unit_list\x12\x06.Query\x1a\t.UnitList\x12\x32\n\rexchange_to_g\x12\x14.UserLikeIngredients\x1a\x0b.Ingredient\x12#\n\nget_recipe\x12\x0c.Ingredients\x1a\x07.Recipeb\x06proto3')



_SIMQUERYRESP = DESCRIPTOR.message_types_by_name['SimQueryResp']
_QUERY = DESCRIPTOR.message_types_by_name['Query']
_UNITLIST = DESCRIPTOR.message_types_by_name['UnitList']
_INGREDIENT = DESCRIPTOR.message_types_by_name['Ingredient']
_INGREDIENTS = DESCRIPTOR.message_types_by_name['Ingredients']
_INGREDIENTS_INGREDIENTSENTRY = _INGREDIENTS.nested_types_by_name['IngredientsEntry']
_USERLIKEINGREDIENTS = DESCRIPTOR.message_types_by_name['UserLikeIngredients']
_RECIPE = DESCRIPTOR.message_types_by_name['Recipe']
SimQueryResp = _reflection.GeneratedProtocolMessageType('SimQueryResp', (_message.Message,), {
  'DESCRIPTOR' : _SIMQUERYRESP,
  '__module__' : 'rec_recipe_pb2'
  # @@protoc_insertion_point(class_scope:SimQueryResp)
  })
_sym_db.RegisterMessage(SimQueryResp)

Query = _reflection.GeneratedProtocolMessageType('Query', (_message.Message,), {
  'DESCRIPTOR' : _QUERY,
  '__module__' : 'rec_recipe_pb2'
  # @@protoc_insertion_point(class_scope:Query)
  })
_sym_db.RegisterMessage(Query)

UnitList = _reflection.GeneratedProtocolMessageType('UnitList', (_message.Message,), {
  'DESCRIPTOR' : _UNITLIST,
  '__module__' : 'rec_recipe_pb2'
  # @@protoc_insertion_point(class_scope:UnitList)
  })
_sym_db.RegisterMessage(UnitList)

Ingredient = _reflection.GeneratedProtocolMessageType('Ingredient', (_message.Message,), {
  'DESCRIPTOR' : _INGREDIENT,
  '__module__' : 'rec_recipe_pb2'
  # @@protoc_insertion_point(class_scope:Ingredient)
  })
_sym_db.RegisterMessage(Ingredient)

Ingredients = _reflection.GeneratedProtocolMessageType('Ingredients', (_message.Message,), {

  'IngredientsEntry' : _reflection.GeneratedProtocolMessageType('IngredientsEntry', (_message.Message,), {
    'DESCRIPTOR' : _INGREDIENTS_INGREDIENTSENTRY,
    '__module__' : 'rec_recipe_pb2'
    # @@protoc_insertion_point(class_scope:Ingredients.IngredientsEntry)
    })
  ,
  'DESCRIPTOR' : _INGREDIENTS,
  '__module__' : 'rec_recipe_pb2'
  # @@protoc_insertion_point(class_scope:Ingredients)
  })
_sym_db.RegisterMessage(Ingredients)
_sym_db.RegisterMessage(Ingredients.IngredientsEntry)

UserLikeIngredients = _reflection.GeneratedProtocolMessageType('UserLikeIngredients', (_message.Message,), {
  'DESCRIPTOR' : _USERLIKEINGREDIENTS,
  '__module__' : 'rec_recipe_pb2'
  # @@protoc_insertion_point(class_scope:UserLikeIngredients)
  })
_sym_db.RegisterMessage(UserLikeIngredients)

Recipe = _reflection.GeneratedProtocolMessageType('Recipe', (_message.Message,), {
  'DESCRIPTOR' : _RECIPE,
  '__module__' : 'rec_recipe_pb2'
  # @@protoc_insertion_point(class_scope:Recipe)
  })
_sym_db.RegisterMessage(Recipe)

_RECRECIPE = DESCRIPTOR.services_by_name['RecRecipe']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INGREDIENTS_INGREDIENTSENTRY._options = None
  _INGREDIENTS_INGREDIENTSENTRY._serialized_options = b'8\001'
  _SIMQUERYRESP._serialized_start=20
  _SIMQUERYRESP._serialized_end=72
  _QUERY._serialized_start=74
  _QUERY._serialized_end=96
  _UNITLIST._serialized_start=98
  _UNITLIST._serialized_end=123
  _INGREDIENT._serialized_start=125
  _INGREDIENT._serialized_end=179
  _INGREDIENTS._serialized_start=181
  _INGREDIENTS._serialized_end=298
  _INGREDIENTS_INGREDIENTSENTRY._serialized_start=248
  _INGREDIENTS_INGREDIENTSENTRY._serialized_end=298
  _USERLIKEINGREDIENTS._serialized_start=300
  _USERLIKEINGREDIENTS._serialized_end=365
  _RECIPE._serialized_start=367
  _RECIPE._serialized_end=403
  _RECRECIPE._serialized_start=406
  _RECRECIPE._serialized_end=577
# @@protoc_insertion_point(module_scope)
